Build system: Fix various wxwidgets find and build issues on Wine/MinGW/MSYS
The find issue on this platform was that find_file(... PATHS
${wxWidgets_INCLUDE_DIRS}) did not work correctly when
${wxWidgets_INCLUDE_DIRS} was in POSIX drive letter form (e.g.,
/z/...) and had to be converted to the colon drive letter form (e.g.,
z:/).  And similarly there were build issues concerning
wxWidgets_INCLUDE_DIRS such as the the wxwidgets version >= 3.0.0
check.  The cure was to convert wxWidgets_INCLUDE_DIRS to the colon
form and append that converted list to the original, i.e., both forms
are in the list where it is assumed one or the other will work on all
platforms.

Another independent build issue concerned "cannot convert" LPCTSTR
LPCWSTR issues.  This happened because the CMake logic line

list(APPEND wxWidgets_DEFINITIONS UNICODE _UNICODE)

in cmake/modules/FindwxWidgets.cmake was buried so deep in Boolean
logic that it was not executed for this platform (at least for the
"MSYS Makefiles" case).

I cured that issue by inserting (in cmake/modules/wxwidgets.cmake)
if(WIN32)
  list(APPEND wxWidgets_DEFINITIONS UNICODE _UNICODE)
endif(WIN32)

where the Boolean logic is much simpler/clearer.  But we may need
to review this fix later.

Tested by: Alan W. Irwin <airwin@users.sourceforge.net> on Wine/MinGW/MSYS
where  the Wine version was Wine Staging 2.10, the MinGW/MSYS
version was a still-working 4.7.2 snapshot from years ago, and
the wxwidgets-3.0.2 libraries were epa_built (without issues)
on this platform.  The test was to run

bash.exe-3.1$ pushd /z/home/software/plplot/HEAD/plplot.git/cmake/epa_build/setup; source setup_msys_makefiles ; popd

to set up all necessary environment variables for this platform.  Then run

bash.exe-3.1$ ${EPA_BUILD_SOURCE_PATH}/../../scripts/comprehensive_test.sh --prefix comprehensive_test_disposable --generator_string "MSYS Makefiles" --cmake_added_options "-DDEFAULT_NO_DEVICES=ON -DPLD_wxwidgets=ON -DDEFAULT_NO_BINDINGS=ON -DENABLE_wxwidgets=ON -DENABLE_cxx=ON -DPAUSE_CERTAIN_INTERACTIVE_DEVICES=ON" --build_command make --ctest_command ctest --do_nondynamic no --do_static no --do_test_noninteractive no --do_ctest no --do_test_install_tree no --do_test_traditional_install_tree no

These script options mean the results are limited to the wxwidgets components
of PLplot, and to speed the test (for now) just interactive testing is
done for just the shared libraries case and just the build tree.

The test_interactive target failed in the build tree, and
comprehensive_test_disposable/shared/interactive/output_tree/make_interactive.out
showed there were no more "cannot convert" LPCTSTR
LPCWSTR issues, but also showed the following issue:

z:/home/software/plplot/HEAD/plplot.git/drivers/wxwidgets_dev.cpp: In constructor 'Rand::Rand()':
z:/home/software/plplot/HEAD/plplot.git/drivers/wxwidgets_dev.cpp:640:25: error: 'rand_s' was not declared in this scope

I followed up by attempting to build the simple rand_s example given at
<https://msdn.microsoft.com/en-us/library/sxtz2fa8.aspx>, but that failed
with similar errors.  The above line was actually in code that worked for
Phil Rosenberg on the MSVC platform just before the PLplot-5.12.0 release,
and I suspect it still works for that platform, but perhaps g++ is much more
stringent about scoping issues?  Anyhow, we may need some C++ scoping expertise
(which I don't have) to sort out this issue.

N.B. Further tests on MSVC and MinGW-w64/MSYS2 are requested, and I currently
predict the former will work, and the latter will run into the above scoping
issue detected by g++.