Fix bug in octave binding
For octave 4.4, I was obtaining the following result when building the
test_octave_xwin target.

Testing interactive octave examples for device xwin
p1
p2
p3
p8
p9
p12
error: string(1): out of bound 0
error: called from
    ginput at line 56 column 11
    p12 at line 27 column 9

where line 56 of  bindings/octave/PLplot/ginput.m
was

str = double(string(1));

and the issue was string was empty (which apparently it always is if
you click with a mouse button).  I fixed this issue by making sure
that string(1) was not converted by double unless string had a
non-zero length.

Tested by: Alan W. Irwin <airwin@users.sourceforge.net> on Linux
(Debian Testing) by successfully building the test_octave_xwin target.